version: "3"
services:
  event-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: event-api
    volumes:
      - ./:/var/www/app:cached
      - /var/www/app/node_modules # anonymous volume for node_modules only
    restart: always
    environment:
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DB=events-db
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=123Qweqq!
      - POSTGRESQL_HOST=postgres
      - REDIS_URL=redis://redis:6379
    ports:
      - 3000:3000
    depends_on:
      - postgres  
      - redis
  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    ports:
      - 8080:80

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: events-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123Qweqq!
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - ./:/data/postgres
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"